### ISSUE TITLE
Missing schema data in Zenodo bundle?

### ISSUE THREAD

**Issue by gklyne** [mapping-manuscript-migrations/mmm-fuseki#1]
The Docker recipe references files that don't appear to be included in the Zenodo "mmm_data" bundle at https://doi.org/10.5281/zenodo.3632944:

```
 && $TDBLOADER --graph=http://ldf.fi/schema/mmm/ /tmp/mmm-schema.ttl \
 && $TDBLOADER --graph=http://ldf.fi/schema/mmm/ /tmp/cidoc-crm.rdf \
 && $TDBLOADER --graph=http://ldf.fi/schema/mmm/ /tmp/frbroo.rdf \
```

For now, I'm planning to use files that appear in this repo, but that requires changes to the Dockerfile.

**Comment by yoge1** [comment]
Indeed, the schema files aren't included in the Zenodo "mmm_data" bundle (actually one of them, the "mmm schema" is, but with a different file name schema.ttl). However, the Dockerfile uses the schema files in this repo - see the line: https://github.com/mapping-manuscript-migrations/mmm-fuseki/blob/aeacf1d178ff8ae551c3604e95a7b18c26163bb2/Dockerfile#L5 so there is no need to make any changes to Dockerfile.

**Comment by gklyne** [comment]
OK, I missed the COPY command you point out.

But, I still question the publication of the dataset in Zenodo without including the relevant schema files.  It seems I might as well go to the GitHub repo and ignore the Zenodo-published dataset?  I was assuming I could use the Dockerfile recipe commands with just the "official" Zenodo-published data.

**Comment by yoge1** [comment]
Fair point. It's definitely a good idea to include all the relevant schema files in the Zenodo-published dataset. We will add the CIDOC CRM and FRBRoo schema files to the next version of the dataset in Zenodo, and update the Dockerfile accordingly.

Also, in addition to the MMM data and schema files, the Dockerfile uses the Fuseki configuration files (fuseki-config.ttl and assembler.ttl) in this GitHub repo, so they will still be needed if you would be using the Dockerfile recipe commands with just the Zenodo-published data.

**Comment by gklyne** [comment]
Ack.  In my case, I was using your Fuseki recipe as a basis for loading the MMM data into a Blazegraph instance.  (Sometimes, running code is the best documentation :) )

**Comment by razz0** [comment]
The schema files are now included in the [dataset in Zenodo](https://zenodo.org/record/4019643) and the filenames match the ones expected in this repository.
